(libvirt) Modify libvirt_wrapper.create_pool to use permission defaults
Libvirt will generate a directory storage pool with 0711 permissions
(and uid/gid of the libvirtd process) by default. Creating the
directories with 0750 is too restrictive and causes terraform
libvirt_domain resource creation to fail with:

```
Error: error creating libvirt domain: Cannot access storage file '/var/lib/libvirt/images/ubuntu-2404-amd64.pool/vm-image.test-singular-ubuntu-2404-amd64-primary.qcow2' (as uid:64055, gid:993): Permission denied

  with module.primary.libvirt_domain.domain,
  on modules/vm/main.tf line 33, in resource "libvirt_domain" "domain":
  33: resource "libvirt_domain" "domain" {
```